export const GROUP_AVERAGE_SERIES_CONFIG = [
	{
		displayName: 'Avg Bat Current',
		internalId: 'avg_current',
		dataKey: 'avg_current',
		unit: 'A',
		decimals: 0,
		color: '#0000b3',
		yAxisIndex: 0,
	},
	{
		displayName: 'Avg Motor Current',
		internalId: 'avg_motor_current',
		dataKey: 'avg_motor_current',
		unit: 'A',
		decimals: 0,
		color: '#8080ff',
		yAxisIndex: 0,
	},
	{
		displayName: 'Avg RPM',
		internalId: 'avg_rpm',
		dataKey: 'avg_rpm',
		unit: 'RPM',
		decimals: 0,
		color: 'green',
		yAxisIndex: 1,
	},
	{
		displayName: 'Avg Speed',
		internalId: 'avg_speed_kmh',
		dataKey: 'avg_speed_kmh',
		unit: 'km/h',
		decimals: 1,
		color: '#fcad03',
		yAxisIndex: 2,
	},
	{
		displayName: 'Avg Voltage',
		internalId: 'avg_volt',
		dataKey: 'avg_volt',
		unit: 'V',
		decimals: 1,
		color: 'grey',
		yAxisIndex: 3,
	},
	{
		displayName: 'Avg Throttle',
		internalId: 'avg_throttle',
		dataKey: 'avg_throttle',
		unit: '',
		decimals: 0,
		color: '#03fcca',
		yAxisIndex: 4,
	},
	{
		displayName: 'Motor/Bat Current Efficiency',
		internalId: 'motor_battery_current_efficiency',
		dataKey: 'motor_battery_current_efficiency',
		unit: '',
		decimals: 1,
		color: '#E57373',
		yAxisIndex: 6,
	},
	{
		displayName: 'Wh/km',
		internalId: 'watt-hour_per_km',
		dataKey: 'watt-hour_per_km',
		unit: '',
		decimals: 0,
		color: '#660000',
		yAxisIndex: 7,
	},
	{
		displayName: 'Watt/Speed',
		internalId: 'watt_per_speed',
		dataKey: 'watt_per_speed',
		unit: '',
		decimals: 0,
		color: '#ff9933',
		yAxisIndex: 8,
	},
	// {
	// 	displayName: 'Distance',
	// 	internalId: 'distance_km',
	// 	dataKey: 'distance_km',
	// 	unit: 'km',
	// 	decimals: 2,
	// 	color: '#33FFBD',
	// 	yAxisIndex: 9,
	// },
	// {
	// 	displayName: 'Duration',
	// 	internalId: 'duration_s',
	// 	dataKey: 'duration_s',
	// 	unit: 's',
	// 	decimals: 0,
	// 	color: '#33D4FF',
	// 	yAxisIndex: 10,
	// },
] as const

export type GroupAverageSeriesConfig = (typeof GROUP_AVERAGE_SERIES_CONFIG)[number]
