from typing import Callable, Any, Optional, Tuple

def start_new_thread(function: Callable, args: Tuple = ()) -> int: ...
def exit() -> None: ...
def allocate_lock() -> Any: ...
def get_ident() -> int: ...
def stack_size(size: Optional[int] = None) -> int: ...
