from typing import Optional, Union, Callable, Tuple, Any, NoReturn

# Pin related constants
IN: int = 0
OUT: int = 1
PULL_UP: int = 1
PULL_DOWN: int = 2
IRQ_RISING: int = 1
IRQ_FALLING: int = 2

class Pin:
    IN: int = IN
    OUT: int = OUT
    PULL_UP: int = PULL_UP
    PULL_DOWN: int = PULL_DOWN
    IRQ_RISING: int = IRQ_RISING
    IRQ_FALLING: int = IRQ_FALLING
    
    def __init__(self, id: Union[int, str], mode: int = -1, pull: int = -1, value: Optional[int] = None) -> None: ...
    def init(self, mode: int = -1, pull: int = -1, value: Optional[int] = None) -> None: ...
    def value(self, x: Optional[int] = None) -> Optional[int]: ...
    def on(self) -> None: ...
    def off(self) -> None: ...
    def irq(self, handler: Optional[Callable] = None, trigger: int = IRQ_FALLING | IRQ_RISING, priority: int = 1) -> Any: ...

def reset() -> NoReturn: ...
def freq(hz: Optional[int] = None) -> int: ...
def unique_id() -> bytes: ...

# Additional common machine module elements
def idle() -> None: ...
def deepsleep(time_ms: Optional[int] = None) -> NoReturn: ...
def disable_irq() -> int: ...
def enable_irq(state: Optional[int] = None) -> None: ...
def time_pulse_us(pin: Pin, pulse_level: int, timeout_us: int = 1000000) -> int: ...
