from typing import Tuple, Optional, List

STA_IF: int
AP_IF: int

class WLAN:
    def __init__(self, interface_id: int) -> None: ...
    def active(self, is_active: Optional[bool] = None) -> bool: ...
    def connect(self, ssid: str, password: str) -> None: ...
    def disconnect(self) -> None: ...
    def scan(self) -> List[Tuple]: ...
    def status(self) -> int: ...
    def isconnected(self) -> bool: ...
    def ifconfig(self) -> Tuple[str, str, str, str]: ...
